### ISSUE TITLE
Profile image is store in individual folder

### ISSUE THREAD

**Issue by exiang** [mymagic/open_hub#15]
After login to member control panel, go to Settings -> Profile.
Uploaded image should be store in profile but not individual.

e.g:
https://mymagic-hub.s3.amazonaws.com/uploads/individual/thumbnail/8bd369d3c2cd2f662fcd197e060a17a1f7c3c4aa.adaptiveResize.80x80.jpg?rand=2757

**Comment by mrpakwan** [comment]
profile image uploaded into the correct folder (profile). connectCallback would not replaced updated avatar. issue fixed.
