### ISSUE TITLE
script can set access control which will be use in module upgrade/system migration

### ISSUE THREAD

**Issue by exiang** [mymagic/open_hub#22]
something like:

AccessController::set('openHub','BackendController',array('upgrade', 'doUpgrade'), array('developer', 'superAdmin'));

**Comment by mrpakwan** [comment]
function & usage
// Access::setAccessRole('[moduleCode]','controller_file',['action1','action2'],['role1','role2']);
Access::setAccessRole('todo','TodoController',['index','admin'],['admin','developer']);

**Comment by mrpakwan** [comment]
issue fixed
