### ISSUE TITLE
default ACL not set according to code prior to update issue

### ISSUE THREAD

**Issue by exiang** [mymagic/open_hub#25]
Make sure changes of this fix auto apply in migration form.

**AdminController**
_isSuperAdmin OR isAdminManager_
admin', 'create', 'createConnect', 'view', 'block', 'blockConfirmed', 'unblock', 'unblockConfirmed',
'resetPassword', 'resetPasswordConfirmed'

Please check on other controllers as well, making sure default access for roles in db is matching with the code in original (commented as now)
```
array('allow', // allow authenticated user to perform 'create', 'update', 'admin' and 'delete' actions
    'actions' => array('view', 'create', 'update', 'admin'),
    'users' => array('@'),
    // 'expression' => '$user->isSuperAdmin==true || $user->isAdmin==true',
    'expression' => 'HUB::roleCheckerAction(Yii::app()->user->getState("rolesAssigned"), Yii::app()->controller)',
),

```

**Comment by mrpakwan** [comment]
have run through all `Controller` and update the default ACL accordingly. issue fixed
