### ISSUE TITLE
[resource] Create resource in resource frontend selecting child categories issue

### ISSUE THREAD

**Issue by exiang** [mymagic/open_hub#26]
The problem only exists in cpanel but not backend

This is a screenshot from backend. if working fine, selecting Main Type: award will only allow you to choose its subcategories which are: awards, competition, certification

<img width="936" alt="Screenshot 2020-06-17 at 12 40 18 PM" src="https://user-images.githubusercontent.com/5336690/84855895-db0f8880-b097-11ea-96c9-4c970185fe31.png">

**Comment by mrpakwan** [comment]
render same create new resource form (in cpanel) for frontend user. issue fixed.
